FORMAT: 1A
HOST: http://sweetify.apiblueprint.org/

# sweetify

sweetify is an API designed on top of Spotify to return information on the top hits for each year

## Songs [/songs/?song_name={string, optional}&artist_name={string, optional}]

### Get all songs, information on a song by name, or all the songs by an artist [GET]

+ Parameters
    + song_name (string, optional) - The song name you want information on; if none provided, returns a list of all songs
    + artist_name (string, optional) - The artist whose songs you want to view

+ Response 200 (application/json)

        {
            "result": {
                "songs": [
                    "Once Dance",
                    "Single Ladies",
                    "Survivor"
                ],
            }
            "success": true
        }

+ Response 200 (application/json)

        {
            "result": {
                "song_name":"One Dance"
                "album": "Views",
                "artist": "Drake",
                "explicit": true,
                "popularity": "75"
            }
            "success": true
        }

+ Response 200 (application/json)

        {
            "result": {
                "artist": "Drake"
                "songs": [
                    {
                        "song_name": "One Dance" 
                        "album": "Views",
                        "artist": "Drake",
                        "explicit": true,
                        "popularity": "75"
                    },
                    {
                        "song_name": "Hello"
                        "album": "Views",
                        "artist": "Drake",
                        "explicit": true,
                        "popularity": "50"
                    }
                ],
            }
            "success": true
        }

## Artists [/artists/?artist_name={string, optional}]
    
### Get all artists or information on an artist by name [GET]

+ Parameters
    + artist_name (string, optional) - The artist name, if none provided, return lists of artists

+ Response 200 (application/json)

        {
            "result": {
                "artists": [
                    "Drake",
                    "Beyonce"
                ],
            }
            "success": true
        }

+ Response 200 (application/json)

        {
            "result": {
                "artist": "Drake"
                "genre": "Rap",
                "popularity": "50",
                "top_tracks": [
                    "One Dance",
                    "Too Good",
                    "Controlla"
                ],
                "img_url": "https://www.google.com/search?q=drake"
            }
            "success": true
        }

## Years  [/years/?year={int, optional}]

### Get all years or information on a specific year [GET]

+ Parameters
    + year (int, optional) - The year to get information on; if none provided, returns a list of years

+ Response 200 (application/json)

        {
            "result": {
                "years": [
                    2000,
                    2001,
                    2002
                ],
            }
            "success": true
        }
        
+ Response 200 (application/json)

        {
            "result": {
                "year": 2016,
                "top_song": "One Dance",
                "top_song_genre": "Rap",
                "top_artist": "Drake",
                "top_album": "Views"
            }
            "success": true
        }

## Genres [/genres/?genre_name={string, optional}]

### Get all genres or information on a genre [GET]

+ Parameters
    + name (string, optional) - The genre you want information on; if none provided, returns a list of all genres

+ Response 200 (application/json)

        {
            "result": {
                "genres": [
                    "Alternative",
                    "Rock",
                    "Hip Hop"
                ],
            }
            "success": true
        }

+ Response 200 (application/json)

        {
            "result": {
                "genre": "Electro house",
                "years_top_song": [2012, 2000],
                "artists": ["Benny Benassi", "Skrillex"],
                "description": "Electro house is a form of hous music characterized by a prominent bassline and/or kick drum.",
                "related_genres": ["House", "Electro"]
            }
            "success": true
        }
